### ISSUE TITLE
Cluster entities according to sameAs relationships

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#11]
Always list canonical entities with their concepts, now there is one entry in the list for each canonical entity<->concept correspondence (example: Hannah Arendt). Nur tatsächlich vorhandene type-beziehungen (concept-assertions) werden angezeigt. Wenn zwei vorhanden sind, werden zwei angezeigt. Grund: fehlendes Resoning in RDF). Clustern alle, die eine Same as relation haben. Bei klick auf + Symbol sieht man alle einzelnen instanzen.

**Comment by jakob0910** [comment]
The entities are now "clustered". We show the lexicographical lowest entity directly, the others are shown in a tooltip of a plus sign.

**Comment by jnoessner** [comment]
Very nice! 
Just a minor thing:
Could you just use another symbol than a "+" (maybe three dots "..." or something like that). Because I clicked on it 5-10 times wondering why nothing happens until I noticed that 'only' the other ids are shown in the tooltip (which is fine!). And I think we could place this symbol behind the name (not so important).

**Comment by jakob0910** [comment]
We replaced the icon with another one that illustrates a stack. I think it is better to place the icon in front of the name because the icons are aligned one below the other if multiple entities are part of a cluster.
