### ISSUE TITLE
Content browser: Add tooltips for strings in "Name" and "Concepts" columns

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#24]
The user should be able to identify the origin of the strings in the columns "Name" and "Concepts". For instance, when hoovering over "aestheticism" it should show "inpho:name".

What is used for the "name" column is also crucial and probably repository dependent. This should be part of a "loading & set-up" procedure that we should start working on in the future.

**Comment by mniepert** [comment]
Tooltips should also be added for the "Concept-buttons" displaying the URIs of the concepts.

**Comment by jakob0910** [comment]
I added column tooltips to the name and concept column.

It is not so simple to add to tooltips to the "concept buttons" because the tooltips use different style classes. Thus, I replaced the text of the buttons by the short uri. In general, I think it is not a good idea to add tooltips to everything because that could also lead to confusion and decrease the usability of the site.
