### ISSUE TITLE
Tooltips are cut off (Chrome)

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#31]
Many tooltips (with longer strings, URIs etc.) are cut off. Not sure how to solve this at the moment.

**Comment by sztyler** [comment]
Do you mean that the tooltip is not complete visible so the user cannot see the full URIs? - thats strage - I did not notice this problem on the enhancer or linker page (my resolutin is 1920x1200) - can you make a screenshot please?

**Comment by mniepert** [comment]
![tooltip](https://f.cloud.github.com/assets/1134108/173132/0bf325a4-7ad3-11e2-8846-f943d26de93b.png)

**Comment by sztyler** [comment]
thx - this should not happen - I will check this

**Comment by sztyler** [comment]
mm in my case - it is displayed correctly - which browser/browser version/system are you using?
![tooltip](https://f.cloud.github.com/assets/3532545/173159/02ffdbbc-7ad4-11e2-9120-986d852b0397.png)

**Comment by mniepert** [comment]
Chrome/Version 24.0.1312.70/Fedora Linux

**Comment by mniepert** [comment]
It's a Chrome issue under Fedora. It works with Firefox.

**Comment by sztyler** [comment]
Ok - I will check if this problem also occurs on other linux distribution

**Comment by jakob0910** [comment]
Bootstrap supports only these browser:
https://github.com/twitter/bootstrap/wiki/Browser-Compatibility

**Comment by sztyler** [comment]
I think this list is out of date - because we are using currently firefox 18 - but in fact linux is not part of this list...

**Comment by mniepert** [comment]
That's fine! We can close this. It's good that it still looks perfectly fine under Linux (except for this one tiny problem).

**Comment by sztyler** [comment]
reopen - should be fixed

problem appears with chrome

**Comment by mniepert** [comment]
Not anymore. This can be closed. I tested it with Chrome under Linux and Windows.

**Comment by mniepert** [comment]
Sorry, I was wrong. This is still an issue with Chrome.

**Comment by sztyler** [comment]
It takes a lot of time but it is fixed now :) - the solution was simple. The problem was that Chrome does only break the line inside a tooltip if there was a wide-space - typically a url does not have a wide-space^^ - furthermore in opposite to chrome - firefox also breaks the line if there appears a slash (this is the reason why the problem only appears in chrome). So I had to search how to wrap long urls - and the solution is: "word-wrap: break-word;". I only had to add this to the tooltip css part :)

fixed in rev. 29bc864

(server will updated within the next few days)
