### ISSUE TITLE
I don't like the back arrow symbol! :)

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#34]
It's ugly. This should be replaced with a nicer looking button or taken out entirely (especially on the enhancer page where the object URI is currently clickable anyway).

**Comment by mniepert** [comment]
In addition, it doesn't render under Chrome/Windows vista (just showing the typical box)

**Comment by sztyler** [comment]
I noted that the symbol is displayed in differenz ways depending on the system/browser. Any suggestions? an image or any unicode character?

**Comment by mniepert** [comment]
What about getting rid of the symbol altogether? I think Colin's problem
was that when he went back to the content explorer page (which is possible
via the menu button "Content") that he had to start over the search.

**Comment by sztyler** [comment]
You mean you would remove the back symbols on the enhancer/linker/overview page because everyone can switch from the enhancer/linker to the overview by clicking the id (e.g. thinker:t1234) and from the overview page to the search by clicking the menu-button "content"?

I think it is not obviously that the user can click on the id to switch back to the overview page - also it is not typical to press an menu-button to switch back to the search result.

**Comment by mniepert** [comment]
Hm, right. One nice solution might be to have something like this:

http://www.hbogo.com/#movies/

When you move the mouse to the right (or left) side of the screen an arrow fades in. Since LODE's interfaces are bidirectional  Explore <-> Overview <-> Link/Enhance   this might be worth a try.

**Comment by sztyler** [comment]
even via VPN to my private server in USA I cannot access the page ...

To access HBO GO℠, you must reside within the fifty states of the United States of America.
If you reside in this area and are still experiencing difficulties, please contact your television provider.

edit
now it works - its loading...

**Comment by sztyler** [comment]
Now I can see these buttons - I'll see what I can do. I have attachend a screenshot for everyone which does not live in the USA ;)
![Buttons](https://f.cloud.github.com/assets/3532545/173218/151cac92-7ad6-11e2-9293-94d2984c71b3.png)

**Comment by mniepert** [comment]
Thanks! The arrows fade in when you get close to the area which I think is a neat/subtle example of directional navigation.

**Comment by mniepert** [comment]
Is this something that can be used:

http://twitter.github.com/bootstrap/examples/carousel.html

**Comment by jnoessner** [comment]
The problem (as far as I remember) is here that the pages do not change when clicking on the arrow. Thus, everything has to be encoded on just one page. But Timo and Jakob are the experts ;-)...

**Comment by sztyler** [comment]
I've thought about it and I think it is a bad idea to implement the buttons like on the screenshot because the buttons are not visible if the user does not navigate the mouse to the left or right part of the screen furthermore a normal user would not find this buttons rather he/she would use the build-in function of the browser to navigate to the previous page. So I think we should use a simple solution like this... - what do you think?
![newBackButton](https://f.cloud.github.com/assets/3532545/192974/736fb856-7f73-11e2-824a-8ec36b87c0be.png)

**Comment by mniepert** [comment]
Yes, this is fine! There should be a tooltip, too ("Go to overview", "Go to content explorer", ...)

**Comment by sztyler** [comment]
fixed in revision [master 8e7c16f]
