### ISSUE TITLE
Content Explorer list/table problem

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#38]
Example: search for "mind"

Click on the next button.This leads you to the next page. The next button is not grayed even though there are only two pages overall.

**Comment by jakob0910** [comment]
Issue/Enhancemanet #11 has to be completed first.

**Comment by jakob0910** [comment]
This problem is fixed. There is only one scenario which is not directly handled as expected: If the last page of a query has as many entries as the maximal number of entries per page, the "next" button is not deactivated. However, it will be deactivated if one clicks the button.

The only possibility to handle this directly is to query the total number of results for a certain query but this would decrease the performance for many queries when it is not required.
