### ISSUE TITLE
DBPedia error for long names 'The Journal of Neoplatonic Studies' but not for e.g. 'Platonism'

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#52]
If I try to link http://www.linkedhumanities.com/content/entity/entity%3Ae4967 ('The Journal of Neoplatonic Studies') I get a DBPedia is not working error. If I take a shorter value (e.g. http://www.linkedhumanities.com/content/entity/entity%3Ae443) everything works fine.

Obviously too many queries at a time or too many results? Can we do something here (e.g. restrict number of results or something?

Error (snippet):
HttpException: 509 Bandwidth Limit Exceeded <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN"> <html> <head> <title>Error HTTP/1.1 509 Bandwidth Limit Exceeded</title> </head> <body> <h3>Error HTTP/1.1 509 Bandwidth Limit Exceeded</h3><pre> Bandwidth Limit Exceeded URI = '/!sparql/' </pre></body></html> at com.hp.hpl.jena.sparql.engine.http.HttpQuery.execCommon(HttpQuery.java:434) at

**Comment by sztyler** [comment]
In the current version I implemented a lot of stuff to handle those problems.
1. Set an timeout limit of 10 sec for sparql querying (the timer starts after the connection between our server and the dbpedia server is established, if the timeout limit is reached we get an incomplete result - typically if the timeout limit is reached the results comprises still hundreds of entries)
2. Implement a progress bar which represents the progress of loading the linker page. So the user can see what is happening.
3. Increase sparql querying method through better handling of SocketTimeoutExceptions

The problem regarding "The Journal of Neoplatonic Studies" is solved by the timeout limit. The problem was that the program tried to search (sparql querying) with the string "The Journal" - which results in many results, because "The Journal" appears in a lot of abstracts.

Please note that dbpedia is currently really really slow - I don't know why. We get a lot of "SocketTimeout" Exceptions.

All these changes are currently not available in the repository (I think, I will push them into the repo. during the next hours)

**Comment by sztyler** [comment]
fixed on rev. 50d39189

(server will updated within the next few days)
