### ISSUE TITLE
Two SameAs links

### ISSUE THREAD

**Issue by jnoessner** [linkedhumanities/lode#54]
I just noticed problems if i create two sameAs links between Instances. I did so for 'John Abercrombie'. 

Now, LODE correctly displays 2 symbols in the search interface. But when I go to the enhancer interface nothing is displayed for enhancement. 
http://linkedhumanities.com/enhance/thinker:t2463/dbpedia

Probably, because it can not decide which link to take. Now there are 3 possibilities to address that:
1. Forbit more than one sameAs between instances (e.g. by replacing the old one). This is the quickest one
2. Encode in the link with which instance we want to enhane (e.g. http://linkedhumanities.com/enhance/thinker:t2463/dbpedia:something/dbpedia) (this solution is not so good in my opinion)
3. Show the union of BOTH sameAs links for enhancement. This might be a bit tricky. As a consequence, we should only display 1 symbol in the search interface if we choose this alternative.

**Comment by sztyler** [comment]
In the current version it is not possible to create more then one owl:sameAs relation. So the user can defined for each local instance one owl:sameAs relation for each existing external provider (e.g. dbpedia). Hence the user can add to a local instance exactly one owl:sameAs relation which point to an instance which is provided by e.g. dbpedia. If we would have e.g. two provider then the user can also define a second sameAs relation which point to an instance which is provided by the second provider (and so on).

So the described problem will be vanished because the external instances are provided by two different providers - furthermore the interfaces will be improved to handle mutiple sameAs relations (see issue #11).

(Please reopen this issue if you think that the described problem is still available)

(server will updated within the next few days)
