### ISSUE TITLE
Type of links between entities 

### ISSUE THREAD

**Issue by mniepert** [linkedhumanities/lode#67]
There are three sections in the enhancer interface:

Concepts
Datatype properties
Object properties

When users drag and drop concept to concept to create a link, the proposed link types have to be changed. The proper link types between concepts are "subclassof", "disjointWith", "broader" etc. but not sameAs or differentFrom. Please make sure that the link types are appropriate for the respective section in the enhancer.

The links between object properties, for instance, should be "subpropertyof" or "disjointproperties" not sameAs etc.

Please refer to the OWL/RDF(S) standards to make sure that the proposed types make sense.

**Comment by sztyler** [comment]
fixed in rev. a6843b01

Instances (Linker)
- owl:sameAs
- owl:differentFrom

Classes (Enhancer, Concept Section)
- owl:equivalentClass
- owl:disjointWith
- rdfs:subClassOf
- skos:related
- skos:broader
- skos:narrower

Properties (Enhancer, Dataproperties & Objectproperties)
- owl:equivalentProperty
- owl:disjointWith
- owl:inverseOf
- rdfs:subPropertyOf
